name: easy-openvpn
version: 2.3.10-1
summary: An easy-to-manage OpenVPN deployment.
description: |
    OpenVPN snap with management scripts that simplify PKI and client
    management for fast, cheap and disposable VPNs. Based on
    https://github.com/kylemanna/docker-openvpn.
confinement: strict
grade: stable

apps:
    easy-openvpn:
        command: bin/ovpn_run
        daemon: simple
        plugs:
            - network
            - network-bind
            - network-control
            - firewall-control
    setup:
        command: bin/ovpn_setup
    clients:
        command: bin/ovpn_listclients
    add-client:
        command: bin/ovpn_addclient
    show-client:
        command: bin/ovpn_getclient
    status:
        command: bin/ovpn_status

parts:
    packages:
        plugin: nil
        stage-packages:
            - openvpn
            - openssl
            - iptables
    easyrsa:
        plugin: dump
        source: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.3/EasyRSA-3.0.3.tgz 
        organize:
            easyrsa: usr/local/easyrsa/easyrsa
            openssl-1.0.cnf: usr/local/easyrsa/openssl-1.0.cnf
            x509-types: usr/local/easyrsa/x509-types
        prime:
            - usr/local/easyrsa
    scripts:
        plugin: dump
        source: .
        prime:
            - bin/*
